# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
stages:
  - lint
  - test

variables:
  # tell Python-based tools to force color output
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'

.before_script_template: &before_script
  # Ansible refuses to read from a world-writeable folder
  - chmod 0750 $CI_PROJECT_DIR
  # Install tools.
  - pip install -U pip
  - pip install --ignore-installed pipenv
  # Install project dependencies.
  - pipenv install --dev

validate:
  stage: lint
  image: python:3.8
  before_script:
    - *before_script
  script:
    # Run Molecule linter.
    - pipenv run molecule lint

molecule:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  before_script:
    # Install Molecule dependencies for use with GitLab CI
    # which are recommended by the Molecule docs:
    # https://molecule.readthedocs.io/en/latest/ci.html#gitlab-ci
    - apk update && apk add --no-cache
      python3-dev py3-pip gcc git curl build-base
      autoconf automake py3-cryptography linux-headers
      musl-dev libffi-dev openssl-dev openssh
    # Output version string of tools used.
    - docker info
    - python3 --version
    - *before_script
  script:
    # Run Molecule tests.
    - pipenv run molecule test

include:
  # Include file to check REUSE-compliance (https://reuse.software/)
  # by running `reuse lint` in a job called `compliance:reuse:`.
  - project: hifis/templates/gitlab-ci
    file: /templates/reuse-compliance.yml

...
