# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
# Task to restart the HAProxy service.
- name: Restart HAProxy
  become: yes
  service:
    name: "{{ haproxy_name }}"
    state: restarted

...
