# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
# Play to create and provision instance.
- name: Converge
  hosts: all
  tasks:
    - name: "Include haproxy_role"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
  vars:
    frontend_ip: "192.168.33.100"
    backends:
      - backend_name: 'backend_server_1'
        backend_ip: '192.168.33.10'

...
