---
- name: Prepare
  hosts: all
  tasks:
    - name: Install dependencies
      apt:
        name:
          - sudo      # for `become` privilege escalation
          - iproute2  # for gathering network facts
          - gnupg2    # for use with "apt-key export"
          - software-properties-common # for use with "apt-repository"
        state: present
