# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
# Dummy play for verification steps.
- name: Verify
  hosts: all
  tasks:
  - name: Example assertion
    assert:
      that: true

...
